apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubTopic
metadata:
  name: ${PUBSUB?}-topic # {"$ref":"#/definitions/io.k8s.cli.substitutions.topic-subs"}
---
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1 
kind: PubSubSubscription
metadata:
  name: ${PUBSUB?}-subscription # {"$ref":"#/definitions/io.k8s.cli.substitutions.subscription-subs"}
  labels:
    goog-dm: deployment
spec:
  topicRef:
    name: ${PUBSUB?}-topic # {"$ref":"#/definitions/io.k8s.cli.substitutions.topic-subs"}
  ackDeadlineSeconds: 60
  messageRetentionDuration: "1200s"
  retainAckedMessages: true
  expirationPolicy:
    ttl: "86400s"
